name: pull_request.yml
on:
    pull_request:
        branches:
        - main
        - develop
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - name: Run cargo fmt check
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run cargo test
        run: cargo test --all
