//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pasta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub content: String,
    pub file_name: Option<String>,
    pub file_size: Option<i64>,
    pub extension: String,
    pub read_only: bool,
    pub private: bool,
    pub editable: i32,
    pub encrypt_server: i32,
    pub encrypt_client: i32,
    pub encrypted_key: Option<String>,
    pub created: i64,
    pub expiration: i64,
    pub last_read: i64,
    pub read_count: i64,
    pub burn_after_reads: i64,
    pub pasta_type: String,
    pub hide_read_count: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
